// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20260408171841_Change_ForecastCash")]
    partial class Change_ForecastCash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("DAL.Entities.ForecastCash", b =>
                {
                    b.Property<string>("LastUpdatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Forecast")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LastUpdatedDateTime");

                    b.ToTable("ForecastCashes");
                });
#pragma warning restore 612, 618
        }
    }
}
